### ISSUE TITLE
the exception below seen happening in a sporadic fashion

### ISSUE THREAD

**Issue by gullerya** [gullerya/data-tier-list#10]
failed to set 'items' of '[object HTMLTemplateElement]' to '[object Object]' DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLTemplateElement.set items [as items] (http://127.0.0.1:5500/node_modules/just-test/dist/libs/data-tier-list/data-tier-list.min.js:1:518)
    at Views._unsafeSetProperty (http://127.0.0.1:5500/node_modules/just-test/dist/libs/data-tier/views.min.js:1:1681)
    at Views.setViewProperty (http://127.0.0.1:5500/node_modules/just-test/dist/libs/data-tier/views.min.js:1:1138)
    at http://127.0.0.1:5500/node_modules/just-test/dist/libs/data-tier/ties.min.js:1:1453
    at Map.forEach (<anonymous>)
    at Tie.updateViews (http://127.0.0.1:5500/node_modules/just-test/dist/libs/data-tier/ties.min.js:1:934)
    at Tie.processDataChanges (http://127.0.0.1:5500/node_modules/just-test/dist/libs/data-tier/ties.min.js:1:889)
    at http://127.0.0.1:5500/node_modules/just-test/dist/libs/data-tier/ties.min.js:1:261
    at c (http://127.0.0.1:5500/node_modules/just-test/dist/libs/data-tier/object-observer.min.js:1:2103)
    at u.set (http://127.0.0.1:5500/node_modules/just-test/dist/libs/data-tier/object-observer.min.js:1:5695)

**Comment by gullerya** [comment]
fixed
